name: opencloud01
services:
  collabora:
    cap_add:
      - MKNOD
    command:
      - -c
      - coolconfig generate-proof-key ; /start-collabora-online.sh
    entrypoint:
      - /bin/bash
    environment:
      DONT_GEN_SSL_CERT: "YES"
      aliasgroup1: https://wopiserver.example.com:443
      extra_params: |
        --o:ssl.enable=false \
        --o:ssl.ssl_verification=false \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=cloud.example.com
      password: notSecure
      username: admin
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9980/hosting/discovery
    image: docker.io/collabora/code:24.04.13.2.1
    labels:
      traefik.enable: "true"
      traefik.http.routers.collabora.entrypoints: https
      traefik.http.routers.collabora.rule: Host(`collabora.example.com`)
      traefik.http.routers.collabora.service: collabora
      traefik.http.routers.collabora.tls.certresolver: http
      traefik.http.services.collabora.loadbalancer.server.port: "9980"
    logging:
      driver: local
    networks:
      opencloud-net: null
    restart: always
  collaboration:
    command:
      - -c
      - opencloud collaboration server
    depends_on:
      collabora:
        condition: service_healthy
        required: true
      opencloud:
        condition: service_started
        required: true
    entrypoint:
      - /bin/sh
    environment:
      COLLABORATION_APP_ADDR: https://collabora.example.com
      COLLABORATION_APP_ICON: https://collabora.example.com/favicon.ico
      COLLABORATION_APP_INSECURE: "false"
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "false"
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      COLLABORATION_LOG_LEVEL: info
      COLLABORATION_WOPI_SRC: https://wopiserver.example.com
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: opencloud:9233
      OC_URL: https://wopiserver.example.com
    image: docker.io/opencloudeu/opencloud-rolling:2.0.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.collaboration.entrypoints: https
      traefik.http.routers.collaboration.rule: Host(`wopiserver.example.com`)
      traefik.http.routers.collaboration.service: collaboration
      traefik.http.routers.collaboration.tls.certresolver: http
      traefik.http.services.collaboration.loadbalancer.server.port: "9300"
    logging:
      driver: local
    networks:
      opencloud-net: null
    restart: always
    volumes:
      - type: volume
        source: opencloud-config
        target: /etc/opencloud
        volume: {}
  companion:
    environment:
      COMPANION_DATADIR: /tmp/companion/
      COMPANION_DOMAIN: companion.example.com
      COMPANION_ONEDRIVE_KEY: ""
      COMPANION_ONEDRIVE_SECRET: ""
      COMPANION_PROTOCOL: https
      COMPANION_UPLOAD_URLS: ^cloud.example.com/
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    image: docker.io/transloadit/companion:5.5.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.companion.entrypoints: https
      traefik.http.routers.companion.rule: Host(`companion.example.com`)
      traefik.http.routers.companion.service: companion
      traefik.http.routers.companion.tls.certresolver: http
      traefik.http.services.companion.loadbalancer.server.port: "3020"
    logging:
      driver: local
    networks:
      opencloud-net: null
    restart: always
    volumes:
      - type: volume
        source: companion-data
        target: /tmp/companion
        volume: {}
  drawio-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/draw-io/ /apps
    entrypoint:
      - /bin/sh
    image: docker.io/opencloudeu/web-extensions:draw-io-1.0.0
    networks:
      opencloud-net: null
    user: root
    volumes:
      - type: volume
        source: opencloud-apps
        target: /apps
        volume: {}
  externalsites-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/external-sites/ /apps
    entrypoint:
      - /bin/sh
    image: docker.io/opencloudeu/web-extensions:external-sites-1.0.0
    networks:
      opencloud-net: null
    user: root
    volumes:
      - type: volume
        source: opencloud-apps
        target: /apps
        volume: {}
  importer-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/importer/ /apps
    entrypoint:
      - /bin/sh
    image: docker.io/opencloudeu/web-extensions:importer-1.0.0
    networks:
      opencloud-net: null
    user: root
    volumes:
      - type: volume
        source: opencloud-apps
        target: /apps
        volume: {}
  jsonviewer-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/json-viewer/ /apps
    entrypoint:
      - /bin/sh
    image: docker.io/opencloudeu/web-extensions:json-viewer-1.0.0
    networks:
      opencloud-net: null
    user: root
    volumes:
      - type: volume
        source: opencloud-apps
        target: /apps
        volume: {}
  opencloud:
    command:
      - -c
      - opencloud init || true; opencloud server
    depends_on:
      drawio-init:
        condition: service_completed_successfully
        required: true
      externalsites-init:
        condition: service_completed_successfully
        required: true
      importer-init:
        condition: service_completed_successfully
        required: true
      jsonviewer-init:
        condition: service_completed_successfully
        required: true
      progressbars-init:
        condition: service_completed_successfully
        required: true
      unzip-init:
        condition: service_completed_successfully
        required: true
    entrypoint:
      - /bin/sh
    environment:
      COLLABORA_DOMAIN: collabora.example.com
      COMPANION_DOMAIN: companion.example.com
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6
      IDM_ADMIN_PASSWORD: notSecure
      IDM_CREATE_DEMO_USERS: "false"
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: "9233"
      NOTIFICATIONS_SMTP_HOST: mail.example.com
      NOTIFICATIONS_SMTP_INSECURE: "false"
      NOTIFICATIONS_SMTP_PORT: "587"
      NOTIFICATIONS_SMTP_SENDER: OpenCloud notifications <cloud@example.com>
      NOTIFICATIONS_SMTP_USERNAME: cloud@example.com
      OC_ADD_RUN_SERVICES: notifications
      OC_INSECURE: "false"
      OC_LOG_COLOR: "false"
      OC_LOG_LEVEL: info
      OC_LOG_PRETTY: "false"
      OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
      OC_URL: https://cloud.example.com
      ONLYOFFICE_DOMAIN: onlyoffice.example.com
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      PROXY_ENABLE_BASIC_AUTH: "false"
      PROXY_TLS: "false"
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      SEARCH_EXTRACTOR_TYPE: tika
    image: docker.io/opencloudeu/opencloud-rolling:2.0.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.opencloud.entrypoints: https
      traefik.http.routers.opencloud.rule: Host(`cloud.example.com`)
      traefik.http.routers.opencloud.service: opencloud
      traefik.http.routers.opencloud.tls.certresolver: http
      traefik.http.services.opencloud.loadbalancer.server.port: "9200"
    logging:
      driver: local
    networks:
      opencloud-net: null
    restart: always
    volumes:
      - type: bind
        source: /home/jochumdev/.cache/octocompose/opencloud01/template/62af890e42e12634e1d31376837b5049.yaml
        target: /etc/opencloud/apps.yaml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/jochumdev/Projekte/go/octocompose/charts/apps/opencloud-monolith/files/opencloud/app-registry.yaml
        target: /etc/opencloud/app-registry.yaml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/jochumdev/.cache/octocompose/opencloud01/template/bc66831f47489461abd1cd759e9c49b7.yaml
        target: /etc/opencloud/csp.yaml
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/jochumdev/Projekte/go/octocompose/charts/apps/opencloud-monolith/files/opencloud/banned-password-list.txt
        target: /etc/opencloud/banned-password-list.txt
        read_only: true
        bind:
          create_host_path: true
      - type: volume
        source: opencloud-config
        target: /etc/opencloud
        volume: {}
      - type: volume
        source: opencloud-data
        target: /var/lib/opencloud
        volume: {}
  progressbars-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/progress-bars/ /apps
    entrypoint:
      - /bin/sh
    image: docker.io/opencloudeu/web-extensions:progress-bars-1.0.0
    networks:
      opencloud-net: null
    user: root
    volumes:
      - type: volume
        source: opencloud-apps
        target: /apps
        volume: {}
  tika:
    image: docker.io/apache/tika:3.1.0.0-full
    logging:
      driver: local
    networks:
      opencloud-net: null
    restart: always
  unzip-init:
    command:
      - -c
      - cp -R /usr/share/nginx/html/unzip/ /apps
    entrypoint:
      - /bin/sh
    image: docker.io/opencloudeu/web-extensions:unzip-1.0.0
    networks:
      opencloud-net: null
    user: root
    volumes:
      - type: volume
        source: opencloud-apps
        target: /apps
        volume: {}
networks:
  opencloud-net:
    name: opencloud01_opencloud-net
volumes:
  companion-data:
    name: opencloud01_companion-data
  opencloud-apps:
    name: opencloud01_opencloud-apps
  opencloud-config:
    name: opencloud01_opencloud-config
  opencloud-data:
    name: opencloud01_opencloud-data
