version: '3'


output: prefixed

tasks:
  build:
    desc: build the project
    cmds:
      - make client

  sample:
    desc: Create sample incus-compose.yaml
    deps: [build]
    cmds:
      - ./incus-compose generate

  transfer:
    desc: copy to server
    deps: [build]
    cmds:
      - scp incus-compose bjk@10.0.1.10:~/bin/incus-compose
