version: '3'


output: prefixed

tasks:
  build:
    desc: build the project
    cmds:
      - go build -o incus-compose
  install:
    desc: install the project
    deps: [build]
    cmds:
      - cp incus-compose ~/bin/

  sample:
    desc: Create sample incus-compose.yaml
    deps: [build]
    cmds:
      - ./incus-compose generate