version: '3'
vars:
  VERSION: 0.1.0

output: prefixed

tasks:
  build:
    desc: build the project
    cmds:
      - go build -o incus-compose
  install:
    desc: install the project
    deps: [build]
    cmds:
      - go install .

  sample:
    desc: Create sample incus-compose.yaml
    deps: [build]
    cmds:
      - ./incus-compose generate

  site:
    desc: Run hugo dev server
    deps: [build]
    dir: docs
    cmds:
      - hugo server --buildDrafts --disableFastRender

  publish:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags 