services:
  declared:
    image: images:debian/bookworm/cloud
    container_name: declared
    restart: unless-stopped
    networks:
      - incusbr0
    labels:
      com.example.appname: my-test-app


networks:
  incusbr0:
    external: true