name: cloud
project: default
export_path: /var/home/bjk/backup/cloud 
services:
    mydb:
        image: images:ubuntu/noble/cloud
        gpu: true
        cloud_init_user_data_file: mydb.yaml
        snapshot:
            schedule: "@hourly"
            expiry: 2w
        volumes:
            config:
                mountpoint: /config
                pool: default
        binds:
            media:
                type: disk
                source: /var/home/bjk
                target: /media
                shift: true
    myjellyfin:
        image: images:ubuntu/noble/cloud
        gpu: true
        cloud_init_user_data_file: jellyfin.yaml
        snapshot:
            schedule: "@hourly"
            expiry: 2w
        volumes:
            config:
                mountpoint: /config
                pool: default
        binds:
            media:
                type: disk
                source: /var/home/bjk
                target: /media
                shift: true
profiles:
    - default
    - vlan5
