version: "3.8"

services:
  bitwarden:
    image: docker:bitwarden/self-host:2024.8.0-beta
    container_name: bitwarden_unified
    restart: always
    depends_on:
      - db
    env_file:
      - settings.env
    ports:
      - "8888:8080"
    expose:
      - 8080
    volumes:
      - data:/etc/bitwarden
      - logs:/var/log/bitwarden
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.bitwarden.rule=Host(`bitwarden.example.com`)
    #  - traefik.http.services.bitwarden.loadbalancer.server.port=8080
    #  # Optional part for file upload max sizes
    #  - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=50000000
    #  - traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=50000000
    #  - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=50000000
    #  - traefik.http.middlewares.limit.buffering.memResponseBodyBytes=50000000
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.bitwarden.middlewares=local-ipwhitelist@file
  
  db:
    image: docker:postgres:alpine3.18
    container_name: bitwarden_unified_db
    restart: always
    environment:
      POSTGRES_USER: "bitwarden"
      POSTGRES_PASSWORD: "super_strong_password"
      POSTGRES_DB: "bitwarden_vault"    
    volumes:
      - psql:/var/lib/postgresql/data
    #networks:
    #  - proxy

#networks:
#  proxy:
#    external: true

volumes:
  psql:
    x-incus-snapshot:
      schedule: '@hourly'
      expiry: 2d
    driver: incus
    driver_opts: 
      pool: "default"
  data:
    x-incus-snapshot:
      schedule: '@hourly'
      expiry: 2d
    driver: incus
    driver_opts: 
      pool: "default"
  logs:
    x-incus-snapshot:
      schedule: '@hourly'
      expiry: 2d
    driver: incus
    driver_opts: 
      pool: "default"